_commit: v1.12.0-2-gc776178
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
homepageEnabled: false
ingress: false
labels: 'app.kubernetes.io/name: reloader'
name: reloader
namespace: reloader
pvc: false
reloader: true
resources:
- deployments.yaml
- rbac.yaml
- service-accounts.yaml
service: false
serviceAccount: false
upstreamURL: https://github.com/stakater/Reloader
url: https://github.com/charlesthomas/homelab-reloader
