_commit: v1.6.18-4-gf354859
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: true
helmCrds: false
helmName: reloader
helmRelease: reloader
helmRepo: https://stakater.github.io/stakater-charts
helmValues: helm/values.yaml
helmVersion: ''
ingress: false
labels: 'app.kubernetes.io/name: reloader'
name: reloader
namespace: reloader
pvc: false
reloader: false
resources: []
service: false
serviceAccount: false
upstreamURL: https://github.com/stakater/Reloader
url: https://github.com/charlesthomas/homelab-reloader
