---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reloader

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-reloader
commonLabels:
  app.kubernetes.io/name: reloader

images:
  - name: reloader
    newName: ghcr.io/stakater/reloader
    newTag: v1.4.7

resources:
- resources/deployments.yaml
- resources/namespaces.yaml
- resources/rbac.yaml
- resources/service-accounts.yaml
