---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reloader

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-reloader
commonLabels:
  app.kubernetes.io/name: reloader

resources:
- resources/namespaces.yaml
helmCharts:
- name: reloader
  namespace: reloader
  releaseName: reloader
  repo: https://stakater.github.io/stakater-charts
  valuesFile: helm/values.yaml
